client:
  - client/**/*
client-package-json:
  - client/package.json
  - client/package-lock.json
  - client/yarn.lock
server:
  - server/**/*
server-package-json:
  - server/package.json
  - server/package-lock.json
  - server/yarn.lock
docker:
  - ./docker/*
  - docker-compose.yml
